
UPDATE `command` SET `security`=3 WHERE `name`='additem';
UPDATE `command` SET `security`=3 WHERE `name`='announce';
UPDATE `command` SET `security`=3 WHERE `name`='character rename';
UPDATE `command` SET `security`=3 WHERE `name`='character reputation';
UPDATE `command` SET `security`=3 WHERE `name`='character titles';
UPDATE `command` SET `security`=3 WHERE `name`='combatstop';
UPDATE `command` SET `security`=2 WHERE `name`='debug';
REPLACE INTO `command` (`name`, `security`, `help`) VALUES ('debug hostile', 2, 'Syntax: .debug hostile\r\n\r\nDisplays hostile units on target.');
UPDATE `command` SET `security`=3 WHERE `name`='debug play cinematic';
UPDATE `command` SET `security`=3 WHERE `name`='debug play movie';
UPDATE `command` SET `security`=3 WHERE `name`='debug play sound';
UPDATE `command` SET `security`=3 WHERE `name`='event';
UPDATE `command` SET `security`=3 WHERE `name`='event activelist';
UPDATE `command` SET `security`=1 WHERE `name`='gm chat';
UPDATE `command` SET `security`=1 WHERE `name`='modify';
UPDATE `command` SET `security`=3 WHERE `name`='modify bit';
UPDATE `command` SET `security`=3 WHERE `name`='modify drunk';
UPDATE `command` SET `security`=3 WHERE `name`='modify energy';
UPDATE `command` SET `security`=3 WHERE `name`='modify hp';
UPDATE `command` SET `security`=3 WHERE `name`='modify mana';
UPDATE `command` SET `security`=3 WHERE `name`='modify mount';
UPDATE `command` SET `security`=3 WHERE `name`='modify phase';
UPDATE `command` SET `security`=3 WHERE `name`='modify rage';
UPDATE `command` SET `security`=3 WHERE `name`='modify reputation';
UPDATE `command` SET `security`=3 WHERE `name`='modify runicpower';
UPDATE `command` SET `security`=3 WHERE `name`='modify scale';
UPDATE `command` SET `security`=1 WHERE `name`='modify speed';
UPDATE `command` SET `security`=1 WHERE `name`='modify speed all';
UPDATE `command` SET `security`=1 WHERE `name`='modify speed backwalk';
UPDATE `command` SET `security`=1 WHERE `name`='modify speed fly';
UPDATE `command` SET `security`=1 WHERE `name`='modify speed swim';
UPDATE `command` SET `security`=1 WHERE `name`='modify speed walk';
UPDATE `command` SET `security`=3 WHERE `name`='wp event';
UPDATE `command` SET `security`=3 WHERE `name`='wp load';
UPDATE `command` SET `security`=3 WHERE `name`='wp show';
UPDATE `command` SET `security`=3 WHERE `name`='wp unload';
UPDATE `command` SET `security`=1 WHERE `name`='whispers';
UPDATE `command` SET `security`=3 WHERE `name`='unban';
UPDATE `command` SET `security`=3 WHERE `name`='unban account';
UPDATE `command` SET `security`=3 WHERE `name`='unban character';
UPDATE `command` SET `security`=3 WHERE `name`='unban ip';
UPDATE `command` SET `security`=1 WHERE `name`='ticket';
UPDATE `command` SET `security`=1 WHERE `name`='ticket assign';
UPDATE `command` SET `security`=1 WHERE `name`='ticket close';
UPDATE `command` SET `security`=1 WHERE `name`='ticket closedlist';
UPDATE `command` SET `security`=1 WHERE `name`='ticket comment';
UPDATE `command` SET `security`=1 WHERE `name`='ticket delete';
UPDATE `command` SET `security`=1 WHERE `name`='ticket list';
UPDATE `command` SET `security`=1 WHERE `name`='ticket onlinelist';
UPDATE `command` SET `security`=1 WHERE `name`='ticket unassign';
UPDATE `command` SET `security`=1 WHERE `name`='ticket viewid';
UPDATE `command` SET `security`=1 WHERE `name`='ticket viewname';
UPDATE `command` SET `security`=3 WHERE `name`='unaura';
UPDATE `command` SET `security`=3 WHERE `name`='server corpses';
UPDATE `command` SET `security`=3 WHERE `name`='send mail';
UPDATE `command` SET `security`=3 WHERE `name`='reset talents';
UPDATE `command` SET `security`=3 WHERE `name`='repairitems';
UPDATE `command` SET `security`=3 WHERE `name`='reload creature_linked_respawn';
UPDATE `command` SET `security`=3 WHERE `name`='pet';
UPDATE `command` SET `security`=3 WHERE `name`='pet unlearn';
UPDATE `command` SET `security`=3 WHERE `name`='notify';
UPDATE `command` SET `security`=3 WHERE `name`='lookup title';
UPDATE `command` SET `security`=3 WHERE `name`='lookup spell id';
UPDATE `command` SET `security`=3 WHERE `name`='lookup spell';
UPDATE `command` SET `security`=3 WHERE `name`='lookup skill';
UPDATE `command` SET `security`=3 WHERE `name`='lookup item';
UPDATE `command` SET `security`=3 WHERE `name`='lookup faction';
UPDATE `command` SET `security`=3 WHERE `name`='lookup event';
UPDATE `command` SET `security`=3 WHERE `name`='lookup area';
UPDATE `command` SET `security`=3 WHERE `name`='list auras';
UPDATE `command` SET `security`=3 WHERE `name`='list';
UPDATE `command` SET `security`=3 WHERE `name`='learn all lang';
UPDATE `command` SET `security`=3 WHERE `name`='itemmove';
UPDATE `command` SET `security`=2 WHERE `name`='instance unbind';
UPDATE `command` SET `security`=2 WHERE `name`='instance';
UPDATE `command` SET `security`=3 WHERE `name`='guild create';
UPDATE `command` SET `security`=3 WHERE `name`='guild delete';
UPDATE `command` SET `security`=3 WHERE `name`='guild uninvite';
UPDATE `command` SET `security`=3 WHERE `name`='guid';
UPDATE `command` SET `security`=3 WHERE `name`='gobject activate';
UPDATE `command` SET `security`=3 WHERE `name`='gobject delete';
UPDATE `command` SET `security`=3 WHERE `name`='gobject';
UPDATE `command` SET `security`=3 WHERE `name`='gobject info';
UPDATE `command` SET `security`=3 WHERE `name`='gobject near';
UPDATE `command` SET `security`=3 WHERE `name`='gobject target';
UPDATE `command` SET `security`=3 WHERE `name`='go trigger';
UPDATE `command` SET `security`=3 WHERE `name`='go taxinode';
UPDATE `command` SET `security`=3 WHERE `name`='go object';
UPDATE `command` SET `security`=3 WHERE `name`='go grid';
UPDATE `command` SET `security`=3 WHERE `name`='go graveyard';
UPDATE `command` SET `security`=2 WHERE `name`='go creature';
UPDATE `command` SET `security`=1 WHERE `name`='go ticket';
UPDATE `command` SET `security`=3 WHERE `name`='achievement';
UPDATE `command` SET `security`=3 WHERE `name`='achievement checkall';
UPDATE `command` SET `security`=3 WHERE `name`='demorph';
UPDATE `command` SET `security`=3 WHERE `name`='modify standstate';
UPDATE `command` SET `security`=2 WHERE `name`='npc';
UPDATE `command` SET `security`=2 WHERE `name`='npc info';
UPDATE `command` SET `security`=3 WHERE `name`='npc follow';
UPDATE `command` SET `security`=3 WHERE `name`='npc follow stop';
UPDATE `command` SET `security`=3 WHERE `name`='npc say';
UPDATE `command` SET `security`=3 WHERE `name`='npc textemote';
UPDATE `command` SET `security`=3 WHERE `name`='npc whisper';
UPDATE `command` SET `security`=3 WHERE `name`='npc yell';
UPDATE `command` SET `security`=3 WHERE `name`='titles add';
UPDATE `command` SET `security`=3 WHERE `name`='titles current';
UPDATE `command` SET `security`=3 WHERE `name`='titles remove';
UPDATE `command` SET `security`=3 WHERE `name`='titles set mask';